### ISSUE TITLE
Nested AttrDicts don't work

### ISSUE THREAD

**Issue by RafiKueng** [bcj/AttrDict#33]
```
In [17]: a = AttrDict()

In [18]: a.b = AttrDict()

In [19]: a.b.c = "Hi there"

In [20]: a
Out[20]: AttrDict({'b': AttrDict({})})

In [21]: a.b
Out[21]: AttrDict({})

In [22]: a.b.c
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-d34de4f2be62> in <module>()
----> 1 a.b.c

/usr/local/lib/python2.7/dist-packages/attrdict/mixins.pyc in __getattr__(self, key)
     80             raise AttributeError(
     81                 "'{cls}' instance has no attribute '{name}'".format(
---> 82                     cls=self.__class__.__name__, name=key
     83                 )
     84             )

AttributeError: 'AttrDict' instance has no attribute 'c'
```

**Comment by RafiKueng** [comment]
Note: they used to work in v1.2, not in v2 any more.

But it's not needed, just use nested dicts:

```
In [1]: a = AttrDict()

In [2]: a.b = {}

In [3]: a.b
Out[3]: a{}

In [4]: type(a)
Out[4]: attrdict.AttrDict

In [5]: type(a.b)
Out[5]: attrdict.AttrDict
```
